export const QuestionCodes = {
  MaterialTecho: '2',
  MaterialPiso: '3',
  MaterialPared: '4',
  Tenenciavivienda: '1',
  Lacocinaseencuentra: '6',
  Cocinacon: '6',
  Numerodepersonaspordormitorio: '8',
  Habitacionesenlavivienda: '26',
  TipodeAlumbrado: '',
  AccesoaInternet: '',
  Techo: '12',
  Piso: '29',
  Pared: '30',
  Iluminacion: '31',
  Ventilacion: '32',
  FuentedeAguaparaelconsumohumano: '10',
  Tratamientodelaguaparaconsumo: '11',
  AlmacenamientodelAguaparaconsumo: '12',
  Estadodelrecipiente: '13',
  Residuosquesegeneranenlavivienda: '27',
  ManejoderesiduosBiodegradables: '15',
  ManejoresiduosOrdinariosnoreciclables: '16',
  ManejoresiduosReciclables: '27',
  Manejoresiduospeligrosos: '28',
  Eliminacionexcretas: '17',
  DisposicionfinalAguasresidualesdomesticas: '19',
  Convivenciaconanimalesadentrodelacasa: '19',
  Numerodeanimalesvacunados: '29',
  Numerodeanimalesnovacunados: '30',
  Presenciadevectoresyroedoresdentrodelacasa: '32',
  TipodeRiesgodelavivienda: '20',
  Tipodeespacioproductivo: '21',
  Destinodelosproductos: '22',
  Practicasculturalesenelespacioproductivo: '23',
  Actividadesproductivasdentrodelavivienda: '24',
  Participalafamiliadepracticasculturalescolectivas: '25',
};

export const QuestionTypes = {
  selectOne: 1,
  multiSelect: 2,
};
