export const QuestionCodes = {
  Tenenciavivienda: '1',
  MaterialTecho: '2',
  MaterialPiso: '3',
  MaterialPared: '4',
  Presenciadevectoresyroedoresdentrodelacasa: '5',
  Cocinacon: '6',
  Numerodepersonaspordormitorio: '8',
  Techo: '9',
  Piso: '10',
  Pared: '11',
  Iluminacion: '12',
  Ventilacion: '13',
  FuentedeAgua: '14',
  Tratamientoagua: '15',
  AlmacenamientoAguaconsumo: '16',
  Estadodelrecipiente: '17',
  TipodeAlumbrado: '18',
  ManejoderesiduosBiodegradables: '19',
  ManejoresiduosOrdinariosnoreciclables: '20',
  Eliminacionexcretas: '21',
  DisposicionfinalAguasdomesticas: '22',
  Convivenciaconanimalesadentrodelacasa: '23',
  TipodeRiesgodelavivienda: '24',
  Tipodeespacioproductivo: '25',
  Destinodelosproductos: '26',
  Practicasculturalesenelespacioproductivo: '27',
  Actividadesproductivasdentrodelavivienda: '28',
  Participalafamiliadepracticasculturalescolectivas: '29',
  Habitacionesenlavivienda: '30',
  ManejoresiduosReciclables: '31',
  Manejoresiduospeligrosos: '32',
};

export const QuestionTypes = {
  selectOne: 1,
  multiSelect: 2,
};
