export const QuestionPersonCodes = {
  DesarmoniaOccidental: '1',
  Alimentacion: '2',
  SaludVisual: '3',
  SaludAuditivaYComunicativa: '4',
  SaludBucal: '5',
  RiesgoPadecerDiabetes: '6',
  SintomaticoRespiratorio: '7',
  SintomaticoDeMalaria: '8',
  DesparasitacionInterna: '9',
  AntecedentesFamiliares: '10',
  Fuma: '11',
  EstadoNutricional: '12',
  RealizacionDePruebasDeCerologiaYVihEnElUltimoTrimestreGestacional: '13',
  RealizacionRitualOPracticasCulturales: '14',
  CausaDeLaMuerte: '15',
  ColoresSemaforo: '16',
  DesparasitacionExterna: '17',
};
