import {FncpersonFncconperSync} from './FncpersonFncconperSync';
import {FncsalrepSync} from './FncsalrepSync';
import {StatusSync} from './StatusSync';
import {AssociationSync} from './AssociationSync';
import {FnbinfsalSync} from './FnbinfsalSync';
export interface FncpersonSync {
  statusSync?: StatusSync;
  id?: string;
  codigo: string;
  correoElectronico: string;
  fechaNacimiento: string;
  identificacion: string;
  primerApellido: string;
  primerNombre: string;
  segundoApellido: string;
  segundoNombre: string;
  telAlterno: string;
  telCelular: string;
  origenData: string;
  usuarioData: string;
  fncgeneroSync: AssociationSync;
  fnclunindSync: AssociationSync;
  fncocupacSync: AssociationSync;
  fncorganiSync: AssociationSync;
  fncparenSync: AssociationSync;
  fnctipideSync: AssociationSync;
  fucmuniciSync: AssociationSync;
  fvbencueSync: AssociationSync;
  fncsalrepSync: FncsalrepSync;
  fnbinfsalSync: FnbinfsalSync;
  fncpersonFncconperSync: FncpersonFncconperSync;
}
